### ISSUE TITLE
Error after matrixEuclideanDistanceKernelFastPartialOut: an illegal memory access was encountered

### ISSUE THREAD

**Issue by davesullivan41** [georgedimitriadis/t_sne_bhcuda#10]
I receive the error above when running on certain sets of data. If I remove ~10% of the data, the error goes away. Full output below. Unfortunately I cannot share the data I am using that produces this error. 

Has anyone seen this before? Any ways to avoid this error?
```
Read the 32806 x 700 data matrix successfully!
Using current time as random seed...
Using no_dims = 2, perplexity = 30.000000, learning rate = 900.000000, and theta = 0.500000
Computing input similarities...

Device Name = Tesla K80
multiProcessorCount: 13
totalGlobalMem (in MB): 11439.875000
totalGlobalMem (in GB): 11.171753
sharedMemPerBlock (in bytes): 49152
Maximum number of threads per block: 1024
Maximum size of each dimension of a block: 1024 x 1024 x 64
Maximum sizes of each dimension of a grid: 2147483647 x 65535 x 65535
Compute capability of the device = 3.7
canMapHostMemory: TRUE
deviceOverlap: TRUE
GPU memory usage: used = 71.250000 MB, free = 11368.625000 MB, total = 11439.875000 MB

GPU iteration = 0, distance elements calculated = 1076233636
GPU memory usage: used = 4352.125000 MB, free = 7087.750000 MB, total = 11439.875000 MB
Error after matrixEuclideanDistanceKernelFastPartialOut: an illegal memory access was encountered
```

**Comment by georgedimitriadis** [comment]
Hello Dave,

I have been getting this error too. 

You can acttually stop it by removing even one or two samples (at least that was my experience). I never figured out why it was happening.

I am about to release a new version of t-sne that does the cuda part using Anaconda's numba and in this version I have never seen this error.

Hope this helps a little

**Comment by davesullivan41** [comment]
Thank you for the prompt response! I look forward to the upcoming release, but for now will use the workaround of removing a few samples and retrying.

Also, this library is incredibly helpful, so thank you for building and continuing to maintain it.
